Fixed
argoapp-live/argo-docs pull request #32
Opened 2022-05-13 15:40 UTC by seunbayo

2022-05-16 08:22 UTC, rekpero requested changes
@seunbayo some more small comments

2022-05-16 08:22 UTC, rekpero commented on sidebars.js
> +      label: "tutorial",
update this as well

2022-05-16 08:22 UTC, rekpero commented on versioned_docs/version-3.0.0-beta/quick-start/minting-101.md
> +#### Go back to your App by clicking on Launch App.
Elaborate this step a bit like, you need to sign a message that will give you access to the platform, and from next time, you don't have to go through this process of validating and minting the NFT anymore.

Another note here: Transfering the NFT to a different wallet will revoke the access to the platform, you need to hold the NFT if you want to use the platform.

2022-05-16 08:22 UTC, rekpero commented on versioned_docs/version-3.0.0-beta/quick-start/minting-101.md
> +### voila!! You have just minted your NFT
put another note here: if you see an error popping in this step, please refresh the window and just click on find out again, you will be able to view your NFTs and launch the app

2022-05-17 01:28 UTC, seunbayo commented
commit pushed

2022-05-17 02:04 UTC, rekpero approved these changes

2022-05-17 02:04 UTC, merged