added environment variable documentation
argoapp-live/argo-docs pull request #75
Opened 2022-11-10 19:14 UTC by seunbayo

2022-11-11 07:56 UTC, rekpero requested changes
@seunbayo please check my comments

2022-11-11 07:56 UTC, rekpero commented on versioned_docs/version-3.0.0-beta/env-var.md
> +sidebar_label: Environment variable
There is already a page for Env var inside the project category. We don't need this page here. Please transfer all the content to that page

2022-11-11 07:56 UTC, rekpero commented on versioned_docs/version-3.0.0-beta/env-var.md
> +## Domain got Environment
I think you should mention this on the domain page, not here. There is no context with the environment variable in this section.

2022-11-11 07:56 UTC, rekpero commented on versioned_docs/version-3.0.0-beta/env-var.md
> +## Domain got Environment
Also this is only applicable for centralised domains and subdomains

2022-11-11 07:56 UTC, rekpero commented on versioned_docs/version-3.0.0-beta/env-var.md
> +sidebar_label: Environment variable
https://docs.spheron.network/projects/environment-variables

2022-11-12 14:28 UTC, rekpero requested changes
@seunbayo some small fix

2022-11-12 14:28 UTC, rekpero commented on versioned_docs/version-3.0.0-beta/projects/domain-and-https/centralized-domain/overview-custom-domain.md
> +This is only applicable to centralized and subdomains
```suggestion
This is only applicable to centralized domains and subdomains
```

2022-11-12 14:28 UTC, rekpero commented on versioned_docs/version-3.0.0-beta/projects/environment-variables.md
> +<strong>you can add an environment variable by going to Project Settings -> Environment Variables </strong>
```suggestion
<strong>You can add an environment variable by going to Project Settings -> Environment Variables </strong>
```

2022-11-12 20:40 UTC, seunbayo commented
@rekpero  fixed

2022-11-14 12:26 UTC, rekpero approved these changes

2022-11-14 12:26 UTC, merged